[package]
name = "delay-queue-bug"
version = "0.1.0"
authors = ["Antonin Amand <antonin.amand@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = "0.1.22"
futures = "0.1.29"
